//USER ACTION TYPES--------------------------------
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

//PRODUCT ACTION TYPE------------------------------
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_ERROR = "ADD_NEW_PRODUCT_ERROR";
