//USER ACTION TYPES--------------------------------
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

//PRODUCT ACTION TYPE------------------------------
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_ERROR = "ADD_NEW_PRODUCT_ERROR";

export const GET_ALL_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_ERROR = "ADD_NEW_PRODUCT_ERROR";

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";

//NEWS LETTER ACTION TYPE------------------------------
export const NEWS_LETTER_SUCCESS = "NEWS_LETTER_SUCCESS";
export const NEWS_LETTER_ERROR = "NEWS_LETTER_ERROR";
