//USER ACTION TYPES--------------------------------
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";

export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_ERROR = "USER_PROFILE_UPDATE_ERROR";

export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_ERROR = "GET_USER_PROFILE_ERROR";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

//PRODUCT ACTION TYPES------------------------------
export const GET_APLLE_PRODUCTS_SUCCESS = "GET_APLLE_PRODUCTS_SUCCESS";
export const GET_APLLE_PRODUCTS_ERROR = "GET_APLLE_PRODUCTS_ERROR";

export const GET_ANDROID_PRODUCTS_SUCCESS = "GET_ANDROID_PRODUCTS_SUCCESS";
export const GET_ANDROID_PRODUCTS_ERROR = "GET_ANDROID_PRODUCTS_ERROR";

export const GET_JUST_FOR_YOU_SUCCESS = "GET_JUST_FOR_YOU_SUCCESS";
export const GET_JUST_FOR_YOU_ERROR = "GET_JUST_FOR_YOU_ERROR";

export const GET_NEW_ARRIVALS_SUCCESS = "GET_NEW_ARRIVALS_SUCCESS";
export const GET_NEW_ARRIVALS_ERROR = "GET_NEW_ARRIVALS_ERROR";

export const GET_BEST_SELLERS_SUCCESS = "GET_BEST_SELLERS_SUCCESS";
export const GET_BEST_SELLERS_ERROR = "GET_BEST_SELLERS_ERROR";

export const GET_NEW_DESING_TRENDS_SUCCESS = "GET_NEW_DESING_TRENDS_SUCCESS";
export const GET_NEW_DESING_TRENDS_ERROR = "GET_NEW_DESING_TRENDS_ERROR";

export const GET_BASIC_CASES_SUCCESS = "GET_BASIC_CASES_SUCCESS";
export const GET_BASIC_CASES_ERROR = "GET_BASIC_CASES_ERROR";

export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";

//SHOPPING CART ACTION TYPES--------------------------
export const ADD_TO_SHOPPING_CART_SUCCESS = "ADD_TO_SHOPPING_CART_SUCCESS";
export const ADD_TO_SHOPPING_CART_ERROR = "ADD_TO_SHOPPING_CART_ERROR";

export const REMOVE_SHOPPING_CART_SUCCESS = "REMOVE_SHOPPING_CART_SUCCESS";
export const REMOVE_SHOPPING_CART_ERROR = "REMOVE_SHOPPING_CART_ERROR";

export const UPDATE_CART_ITEM_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";
export const UPDATE_CART_ITEM_ERROR = "UPDATE_CART_ITEM_ERROR";

export const PLACE_ORDER_SUCCESS = "UPDATE_CART_ITEM_SUCCESS";
export const PLACE_ORDER_ERROR = "UPDATE_CART_ITEM_ERROR";

//EMAIL SUBSCRIBE ACTION TYPE--------------------------
export const EMAIL_SUBSCRIBE_SUCCESS = "EMAIL_SUBSCRIBE_SUCCESS";
export const EMAIL_SUBSCRIBE_ERROR = "EMAIL_SUBSCRIBE_ERROR";

//HOME PAGE IMAGES ACTION TYPE--------------------------
export const GET_HOMEPAGE_IMGS_SUCCESS = "GET_HOMEPAGE_IMGS_SUCCESS";
export const GET_HOMEPAGE_IMGS_ERROR = "GET_HOMEPAGE_IMGS_ERROR";
