//USER ACTION TYPES--------------------------------
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

//PRODUCT ACTION TYPES------------------------------
export const GET_APLLE_PRODUCTS_SUCCESS = "GET_APLLE_PRODUCTS_SUCCESS";
export const GET_APLLE_PRODUCTS_ERROR = "GET_APLLE_PRODUCTS_ERROR";

export const GET_ANDROID_PRODUCTS_SUCCESS = "GET_ANDROID_PRODUCTS_SUCCESS";
export const GET_ANDROID_PRODUCTS_ERROR = "GET_ANDROID_PRODUCTS_ERROR";

export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";

//SHOPPING CART ACTION TYPES--------------------------
export const ADD_TO_SHOPPING_CART_SUCCESS = "ADD_TO_SHOPPING_CART_SUCCESS";
export const ADD_TO_SHOPPING_CART_ERROR = "ADD_TO_SHOPPING_CART_ERROR";

export const REMOVE_SHOPPING_CART_SUCCESS = "REMOVE_SHOPPING_CART_SUCCESS";
export const REMOVE_SHOPPING_CART_ERROR = "REMOVE_SHOPPING_CART_ERROR";
